/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SplitterConveyor */

#ifndef _Included_SplitterConveyor
#define _Included_SplitterConveyor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SplitterConveyor
 * Method:    initializeHardwarePorts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_initializeHardwarePorts
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinder1MoveForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder1MoveForward
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinder1MoveBackward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder1MoveBackward
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinder1Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder1Stop
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinder2MoveForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder2MoveForward
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinder2MoveBackward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder2MoveBackward
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinder2Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder2Stop
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    conveyorMove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_conveyorMove
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    conveyorStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_conveyorStop
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinderStartMoveForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinderStartMoveForward
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinderStartMoveBackward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinderStartMoveBackward
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinderStartStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinderStartStop
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    ledOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_ledOn
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    ledOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_ledOff
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinderStartGetPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_cylinderStartGetPosition
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinder1GetPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_cylinder1GetPosition
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    cylinder2GetPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_cylinder2GetPosition
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    getIdentificationSensors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_getIdentificationSensors
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    isBoxAtDock1
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_isBoxAtDock1
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    isBoxAtDock2
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_isBoxAtDock2
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    isDock1Closed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_isDock1Closed
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    isDock2Closed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_isDock2Closed
  (JNIEnv *, jclass);

/*
 * Class:     SplitterConveyor
 * Method:    areDocksClosed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_areDocksClosed
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
